import { Link } from "react-router-dom";

/**
 * Brand lockup built from the official 424 TRADING logo assets
 * (transparent PNGs generated by scripts/make-logo.mjs).
 * `dark` renders a white wordmark for dark backgrounds (footer, admin).
 */
export default function Logo({
  dark = false,
  size = "md",
}: {
  dark?: boolean;
  size?: "md" | "lg";
}) {
  const markH = size === "lg" ? "h-14" : "h-9 sm:h-11";
  const wordH = size === "lg" ? "h-7" : "h-4 sm:h-5";

  return (
    <Link
      to="/"
      aria-label="424 TRADING — home"
      className="flex items-center gap-2.5 sm:gap-3 shrink-0 group"
    >
      <img
        src="/media/logo-mark.png"
        alt=""
        className={`${markH} w-auto transition-transform group-hover:scale-105`}
      />
      <span className="leading-none">
        {dark ? (
          <span className="block text-white font-black tracking-tight text-lg sm:text-xl">
            424 TRADING
          </span>
        ) : (
          <img
            src="/media/logo-wordmark.png"
            alt="424 TRADING"
            className={`${wordH} w-auto`}
          />
        )}
        <span
          className={`block mt-1 text-[8px] sm:text-[9px] font-semibold tracking-[0.16em] ${
            dark ? "text-ink-300" : "text-ink-500"
          }`}
        >
          QUALITY PRODUCTS. CONVENIENTLY SOURCED
        </span>
      </span>
    </Link>
  );
}
